config/routes.rb
Rails.application.routes.draw do
  resources :autos

  resources :photos

  root to: "auto_sales#index"
  devise_for :users
  resources :auto_sales

end

app/models/auto.rb
class Auto < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos, :allow_destroy => true
end

app/models/auto_sale.rb
class AutoSale < ActiveRecord::Base
  belongs_to :user
  has_one :auto
  accepts_nested_attributes_for :auto, :allow_destroy => true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :auto
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :auto_sales
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/auto_sales_controller.rb
class AutoSalesController < ApplicationController
  before_action :set_auto_sale, only: [:show, :edit, :update, :destroy]

  def index
    @auto_sales = AutoSale.all
  end

  def show
    @photos = @auto_sale.autos.photos.all
  end

  def new
    @auto_sale = AutoSale.new
  end

  def create
    @auto_sale = AutoSale.new(auto_sale_params)

    respond_to do |format|
      if @auto_sale.save
        format.html { redirect_to @auto_sale, notice: 'Auto sale was successfully created.' }
        format.json { render :show, status: :created, location: @auto_sale }
      else
        format.html { render :new }
        format.json { render json: @auto_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @auto_sale.update(auto_sale_params)
        format.html { redirect_to @auto_sale, notice: 'Auto sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto_sale }
      else
        format.html { render :edit }
        format.json { render json: @auto_sale.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @auto_sale.destroy
    respond_to do |format|
      format.html { redirect_to auto_sales_url, notice: 'Auto sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_auto_sale
      @auto_sale = AutoSale.find(params[:id])
    end

    def auto_sale_params
      params.require(:auto_sale).permit(:title, :price,
        auto_attributes: [:name, :year, :madein, :type, :color, :went, :description]
        )
    end
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :set_auto, only: [:show, :edit, :update, :destroy]

  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.all
  end

  # GET /autos/1
  # GET /autos/1.json
  def show
  end

  # GET /autos/new
  def new
    @auto = Auto.new
  end

  # GET /autos/1/edit
  def edit
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(auto_params)

    respond_to do |format|
      if @auto.save
        format.html { redirect_to @auto, notice: 'Auto was successfully created.' }
        format.json { render :show, status: :created, location: @auto }
      else
        format.html { render :new }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autos/1
  # PATCH/PUT /autos/1.json
  def update
    respond_to do |format|
      if @auto.update(auto_params)
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto }
      else
        format.html { render :edit }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto.destroy
    respond_to do |format|
      format.html { redirect_to autos_url, notice: 'Auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto
      @auto = Auto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_params
      params.require(:auto).permit(:name, :year, :madein, :type, :color, :went, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auto_sales_helper.rb
module AutoSalesHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/auto_sales/_form.html.erb
<%= form_for(@auto_sale) do |f| %>
  <% if @auto_sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auto_sale.errors.count, "error") %> prohibited this auto_sale from being saved:</h2>

      <ul>
      <% @auto_sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>

  <%= f.fields_for :auto, f.object.build_auto, :html => { :multipart => true } do |auto_fields| %>
    <%= t('Car for sale') %> <br />
    <%= auto_fields.text_field :name %><br />

    <%= t('Mode year') %> <br />
    <%= auto_fields.select :year, options_for_select(Settings.data.year) %> </br />

    <%= t('Made in') %> <br />
    <%= auto_fields.select :madein, options_for_select(Settings.data.madein) %><br />

    <%= t('Type') %> <br />
    <%= auto_fields.select :type, options_for_select(Settings.data.modeltype) %><br />

    <%= t('Color') %> <br />
    <%= auto_fields.select :color, options_for_select(Settings.data.color) %><br />

    <%= t('Went') %> <br />
    <%= auto_fields.number_field :went %><br />

    <%= t('Description') %> <br />
    <%= auto_fields.text_field :description %><br />

    <%= auto_fields.fields_for :photos, auto_fields.object.photos.new do |p| %>
      <div class="field">
        <%= p.label :avatar %><br>
        <%= p.file_field :avatar, :multiple => true, name: "photos[avatar][]" %>
     </div>
   <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auto_sales/edit.html.erb
<h1>Editing auto_sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @auto_sale %> |
<%= link_to 'Back', auto_sales_path %>

app/views/auto_sales/index.html.erb
<h1>Listing auto_sales</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Auto</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auto_sales.each do |auto_sale| %>
      <tr>
        <td><%= link_to auto_sale.title, auto_sale %></td>
        <td><%= auto_sale.auto.name %> <%= auto_sale.auto.year %></td>
        <td><%= auto_sale.price %> <%= "Triệu" %></td>
        <td><%= auto_sale.auto.went %> <%= "Km" %></td>
        <td><%= auto_sale.auto.color %></td>
        <td><%= auto_sale.auto.type %></td>

<!--         <% if auto_sale.owned_by? current_user %>
          <td><%= link_to t('Edit'), edit_auto_sale_path(auto_sale) %></td>
          <td><%= link_to t('Destroy'), auto_sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auto sale', new_auto_sale_path %>

app/views/auto_sales/new.html.erb
<h1>New auto_sale</h1>

<%= render 'form' %>

<%= link_to 'Back', auto_sales_path %>

app/views/auto_sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @auto_sale.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @auto_sale.price %>
</p>
<% @photos.each do |p| %>
  <%= image_tag p.avatar_url %>
<% end %>


<%= link_to 'Edit', edit_auto_sale_path(@auto_sale) %> |
<%= link_to 'Back', auto_sales_path %>

app/views/autos/_form.html.erb
<%= form_for(@auto) do |f| %>
  <% if @auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auto.errors.count, "error") %> prohibited this auto from being saved:</h2>

      <ul>
      <% @auto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :madein %><br>
    <%= f.text_field :madein %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :went %><br>
    <%= f.text_field :went %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/autos/edit.html.erb
<h1>Editing auto</h1>

<%= render 'form' %>

<%= link_to 'Show', @auto %> |
<%= link_to 'Back', autos_path %>

app/views/autos/index.html.erb
<h1>Listing autos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Madein</th>
      <th>Type</th>
      <th>Color</th>
      <th>Went</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @autos.each do |auto| %>
      <tr>
        <td><%= auto.name %></td>
        <td><%= auto.year %></td>
        <td><%= auto.madein %></td>
        <td><%= auto.type %></td>
        <td><%= auto.color %></td>
        <td><%= auto.went %></td>
        <td><%= auto.description %></td>
        <td><%= link_to 'Show', auto %></td>
        <td><%= link_to 'Edit', edit_auto_path(auto) %></td>
        <td><%= link_to 'Destroy', auto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auto', new_auto_path %>

app/views/autos/new.html.erb
<h1>New auto</h1>

<%= render 'form' %>

<%= link_to 'Back', autos_path %>

app/views/autos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @auto.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @auto.year %>
</p>

<p>
  <strong>Madein:</strong>
  <%= @auto.madein %>
</p>

<p>
  <strong>Type:</strong>
  <%= @auto.type %>
</p>

<p>
  <strong>Color:</strong>
  <%= @auto.color %>
</p>

<p>
  <strong>Went:</strong>
  <%= @auto.went %>
</p>

<p>
  <strong>Description:</strong>
  <%= @auto.description %>
</p>

<%= link_to 'Edit', edit_auto_path(@auto) %> |
<%= link_to 'Back', autos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :auto_sale_id %><br>
    <%= f.number_field :auto_sale_id %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <thead>
    <tr>
      <th>Auto sale</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.auto_sale_id %></td>
        <td><%= photo.avatar %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Auto sale:</strong>
  <%= @photo.auto_sale_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @photo.avatar %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>